### PR TITLE
Request sensitive configuration

### PR DESCRIPTION
**Pull request by thomaseizinger**
This PR targets issue #14.

As mentioned in the first commit, I moved the example and the test project into the /src folder because the references to the nuget-packages folder where broken inside the solution file. I also added the xunit runner as a dependency to the test project.

It is now possible to do the following:

```
public ExampleModule()
{
	this.Get["/"] = _ => 
    {
        this.Context
        	.LocalHalConfigFor<Users>()
            .Links("relation", "/link");

        return 200;
    };
}
```
The local config will only be honored for the current request.

I added two tests:
https://github.com/thomaseizinger/Nancy.Hal/blob/request-sensitive-configuration/src/Nancy.Hal.Tests/JsonResponseProcessorTests.cs#L163-L178
https://github.com/thomaseizinger/Nancy.Hal/blob/request-sensitive-configuration/src/Nancy.Hal.Tests/JsonResponseProcessorTests.cs#L181-L197

Tell me what you think :)

### CODE REVIEW

**Comment by danbarua** [comment]
Oh that is sweet, I'll take a look tomorrow at work and get it merged in.

**Comment by danbarua** [comment]
v1.1.0 is up on NuGet with this new feature, thanks for contributing. :+1:

**Comment by GraemeF** [comment]
This is great! Thanks guys! :+1:

**Comment by thomaseizinger** [comment]
Thanks for merging this in! :)

**Pull request merged**
